FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Directory.Build.props Directory.Packages.props ./
COPY src/ ./src/
RUN dotnet restore src/CleanArchWebApi.WebApi/CleanArchWebApi.WebApi.csproj
RUN dotnet publish src/CleanArchWebApi.WebApi/CleanArchWebApi.WebApi.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "CleanArchWebApi.WebApi.dll"]
